get_filename_component(c_RootDirPath "${CMAKE_CURRENT_SOURCE_DIR}/../.." ABSOLUTE)
set(RootGeneratedDirPath ${CMAKE_CURRENT_BINARY_DIR}/Generated)
set(RootSourceDirPath ${c_RootDirPath}/Source)
set(RootProjectDirPath ${c_RootDirPath}/Project)
set(RootCMakeDirPath ${c_RootDirPath}/CMake)
set(RootThirdPartyDirPath ${c_RootDirPath}/ThirdParty)