if(WIN32)
	set(ExeName7z 7za.exe)
	set(ExeFilePathZip ${ProjectTempDirPath}/${ExeName7z})
	if(NOT EXISTS "${ExeFilePathZip}")
		set(SrcFilePath ${StorageAddrPath}/Tool/${ProjectPlatform}/7z/${ExeName7z})
		set(DstFilePath ${ExeFilePathZip})
		message(STATUS "Downloading ${DstFilePath} from ${SrcFilePath}")
		file(DOWNLOAD ${SrcFilePath} ${DstFilePath}
			 STATUS status
			 #SHOW_PROGRESS
		)
		if(status EQUAL 0)
			message(STATUS "File downloaded successfully.")
		else()
			message(FATAL_ERROR "File download failed.")
		endif()
	endif()
else()
	set(ExeFilePathZip 7z)
endif()
